User management
itk-dev/datatidy pull request #16
Opened 2019-11-14 15:47 UTC by rimi-itk

https://jira.itkdev.dk/browse/ODAA-75

2019-11-15 23:02 UTC, lats1 requested changes

2019-11-15 23:02 UTC, lats1 commented on src/Security/DataFlowVoter.php
> +        // you know $subject is a Post object, thanks to supports
Sneaky comment from the symfony docs should probably be removed.

2019-11-15 23:02 UTC, lats1 commented on templates/user/_delete_form.html.twig
> +</form>
Missing translations

2019-11-15 23:02 UTC, lats1 commented on templates/user/edit.html.twig
> +    <a href="{{ path('user_index') }}">back to list</a>
Missing translations

2019-11-15 23:02 UTC, lats1 commented on templates/user/index.html.twig
> +                <th>actions</th>
Missing translations

2019-11-15 23:02 UTC, lats1 commented on templates/user/index.html.twig
> +                <td>{{ user.enabled ? 'Yes' : 'No' }}</td>
Missing translations

2019-11-15 23:02 UTC, lats1 commented on templates/user/index.html.twig
> +                    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>
Missing translations

2019-11-15 23:02 UTC, lats1 commented on templates/user/index.html.twig
> +                <td colspan="13">no records found</td>
Missing translations

2019-11-16 09:52 UTC, rimi-itk commented on src/Security/DataFlowVoter.php
> +        // you know $subject is a Post object, thanks to supports
OMG! Busted. Again …

2019-11-16 09:54 UTC, lats1 approved these changes

2019-11-16 09:54 UTC, merged